spring.application.name=pdf-marketplace
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
admin.emails=${ADMIN_EMAILS:}
